logging:
  level:
    org.apache.ibatis: debug
    com.kfayun.app: debug

app:
  context-path:
  upload-path: e:/00nfs/02kfayun/app/witkey/upload/
  tasktopticks-update-cron: 0 0/1 * * * ?
  db:
    server: 10.8.0.1:30781
    database: witkey
    username: witkey
    password: Witkey@135
  spi:
    verify-sender:
      sms:
        sender-clazz: com.kfayun.app.witkey.spi.impl.FakeSmsSender
        config: {}
      email:
        sender-class: com.kfayun.app.witkey.spi.impl.JavaxMailSender
        config: {}